run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gocognit
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - depguard
    - prealloc

linters-settings:
  funlen:
    lines: 80
    statements: 60
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 30
  nestif:
    min-complexity: 8
  lll:
    line-length: 140
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  misspell:
    locale: US
