run:
  go: "1.26"
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  funlen:
    lines: 60
    statements: 40
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 5
  lll:
    line-length: 120
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - unconvert
    - unused
    - whitespace
  disable:
    - depguard
    - prealloc

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
