services:
  database:
    image: postgres:16-alpine
    container_name: outless-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: outless
      POSTGRES_USER: outless
      POSTGRES_PASSWORD: outless
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U outless -d outless" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - outless_network

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: outless-xray
    restart: unless-stopped
    volumes:
      - ./xray.config.json:/etc/xray/config.json:ro
    command: [ "run", "-config", "/etc/xray/config.json" ]
    ports:
      - "443:443"
      - "10085:10085"
    networks:
      - outless_network

  outless:
    container_name: outless
    image: quonaro/outless:backend
    restart: unless-stopped
    depends_on:
      - database
      - xray
    ports:
      - "41220:41220"
    volumes:
      - ./outless.yaml:/outless.yaml:ro
      - geoip_data:/app/tmp
    networks:
      - outless_network

  frontend:
    container_name: outless-frontend
    image: quonaro/outless:frontend
    restart: unless-stopped
    depends_on:
      - outless
    ports:
      - "41221:3000"
    environment:
      - API_BASE_URL=http://outless:41220
    networks:
      - outless_network

volumes:
  postgres_data:
    name: outless-db
  geoip_data:
    name: outless-geoip

networks:
  outless_network:
    name: outless_network
