ALTER TABLE groups
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS total_nodes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS healthy_nodes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS unhealthy_nodes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS unknown_nodes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
